[tool.poetry]
name = "balaambot"
version = "0.1.0"
description = "A discord bot that punishes cussing"
authors = ["James Wild <wild.james343@gmail.com>"]
license = "MIT"
packages = [{include="src"}]

[tool.poetry.scripts]
balaambot = "src.main:start"

[tool.poetry.dependencies]
python = "^3.10"
"discord.py" = "^2.5.2"
anyio = "^4.9.0"
dotenv = "^0.9.9"
pynacl = "^1.5.0"
discord-ext-voice-recv = "^0.4.2a145"
yt-dlp = "^2025.5.22"
pytest-cov = "^6.1.1"
pyjokes = "^0.8.3"

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.11"
pytest = "^8.3.5"
pytest-asyncio = "^0.26.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
